### ISSUE TITLE
Button-3

### ISSUE THREAD

**Issue by ifchang** [a7773077567/animation-buttons#21]
### Desc
- Add hover effect in button-3
---

### Tasks
- [x] layout
- [x] feature
- [x] testing
---

### UI
<img width="184" alt="image" src="https://user-images.githubusercontent.com/82376166/163131593-515f346f-7bfe-436e-9e91-d0fa51edd3b1.png">

---

### Note
- No JS, just pure CSS
- Written by SASS
- Do not modify this card!!!

**Comment by ifchang** [comment]
請讓我做按鈕 拜偷

**Comment by a7773077567** [comment]
GO!
