### ISSUE TITLE
Button-15

### ISSUE THREAD

**Issue by ifchang** [a7773077567/animation-buttons#22]
### Desc
- Add hover effect in button-15
---

### Tasks
- [x] layout
- [x] feature
- [x] testing
---

### UI
<img width="187" alt="image" src="https://user-images.githubusercontent.com/82376166/163131745-b149b2ed-8c12-4c1a-b6fa-29f62ad05aa6.png">
---

### Note
- No JS, just pure CSS
- Written by SASS
- Do not modify this card!!!

**Comment by ifchang** [comment]
讓我看看

**Comment by a7773077567** [comment]
這個也要go嗎?

**Comment by ifchang** [comment]
一次只能go一個嗎

**Comment by a7773077567** [comment]
想go幾個就go幾個, 還可以再幫你多加1個喔!

**Comment by ifchang** [comment]
go吧 gogo power ranger~~

**Comment by a7773077567** [comment]
OK!
精肛戰士? 小心暴露年齡!

**Comment by ifchang** [comment]
這部跟我小時候看的有些不一樣
