### ISSUE TITLE
test issue

### ISSUE THREAD

**Issue by yoshuu** [a7773077567/animation-buttons#8]
### Desc
- Add hover effect in button-1
---

### Tasks
- [ ] layout
- [ ] feature
- [ ] testing
---

### UI
<img width="160" alt="截圖 2022-04-12 下午3 46 50" src="https://user-images.githubusercontent.com/55973225/162908397-3dd9d202-30f6-49bb-94be-38b957881521.png">
<img width="181" alt="截圖 2022-04-13 上午11 19 12" src="https://user-images.githubusercontent.com/76735999/163093462-77c359c9-1dfb-4042-88a4-d9c42c8a7b3c.png">

---

### Note
- No JS, just pure CSS
- Written by SASS
- Do not modify this card!!!

**Comment by yoshuu** [comment]
佳憲  comment

**Comment by a7773077567** [comment]
已收
